export type ModelCategory = "chinese" | "american" | "openrouter";

export interface ModelSpec {
  id: string;
  name: string;
  provider: string;
  category: ModelCategory;
  architecture?: string;
  params?: string;
  paramsActive?: string;
  context?: number;
  contextMax?: number;
  capabilities: string[];
  free: boolean;
  description: string;
  site?: string;
}

export const MODELS: ModelSpec[] = [
  // ======= CHINESE MODELS =======
  {
    id: "deepseek/deepseek-r1",
    name: "DeepSeek R1",
    provider: "DeepSeek (深度求索)",
    category: "chinese",
    architecture: "MoE Transformer",
    params: "671B",
    paramsActive: "37B",
    context: 131072,
    capabilities: ["text", "code", "reasoning", "math"],
    free: false,
    description: "ينافس OpenAI المتقدمة بتكلفة تدريب أقل 95%، قوي في التفكير المنطقي المعقد والبرمجة",
  },
  {
    id: "deepseek/deepseek-r1-zero",
    name: "DeepSeek R1 Zero",
    provider: "DeepSeek (深度求索)",
    category: "chinese",
    architecture: "Transformer",
    context: 131072,
    capabilities: ["text", "reasoning", "research", "math"],
    free: true,
    description: "متخصص في الاستدلال العلمي والبحثي والرياضي مع تحقق وسيط متعدد الخطوات",
    site: "https://openrouter.ai/deepseek/deepseek-r1-zero",
  },
  {
    id: "deepseek/deepseek-v3-base:free",
    name: "DeepSeek V3 Base",
    provider: "DeepSeek (深度求索)",
    category: "chinese",
    architecture: "MoE Transformer",
    params: "671B",
    paramsActive: "37B",
    context: 131072,
    capabilities: ["text", "code", "reasoning"],
    free: true,
    description: "نموذج أساسي قوي في المجالات التقنية والبرمجة من أحدث جيل DeepSeek",
    site: "https://openrouter.ai/deepseek/deepseek-v3-base",
  },
  {
    id: "deepseek/deepseek-chat-v3-0324:free",
    name: "DeepSeek Chat V3-0324",
    provider: "DeepSeek (深度求索)",
    category: "chinese",
    architecture: "Transformer",
    context: 131072,
    capabilities: ["text", "dialogue", "code"],
    free: true,
    description: "نسخة محسّنة للحوار مع تتبع حالة المحادثة وإدارة الذاكرة",
    site: "https://openrouter.ai/deepseek/deepseek-chat-v3-0324",
  },
  {
    id: "bytedance/doubao-1.5-pro",
    name: "Doubao 1.5 Pro",
    provider: "ByteDance (بايت دانس)",
    category: "chinese",
    architecture: "Transformer",
    capabilities: ["text", "image", "code", "personalization"],
    free: false,
    description: "من بايت دانس (TikTok)، يتفوق في النصوص والصور والتخصيص، ملايين المستخدمين النشطين",
  },
  {
    id: "qwen/qwen2.5-vl-3b-instruct:free",
    name: "Qwen2.5-VL 3B",
    provider: "Alibaba (علي بابا)",
    category: "chinese",
    architecture: "Vision-Language Transformer",
    params: "3B",
    context: 32768,
    capabilities: ["text", "image", "vision"],
    free: true,
    description: "نموذج مفتوح المصدر متعدد الوسائط، قوي في البرمجة وفهم اللغات",
    site: "https://openrouter.ai/qwen/qwen2.5-vl-3b-instruct",
  },
  {
    id: "qwen/qwq-32b",
    name: "QWQ (Qwen Reasoning)",
    provider: "Alibaba (علي بابا)",
    category: "chinese",
    architecture: "MoE Transformer",
    params: "32B",
    context: 131072,
    capabilities: ["text", "reasoning", "math", "code"],
    free: false,
    description: "نموذج تفكير من عائلة Qwen، قوي في الرياضيات والاستدلال المنطقي",
  },
  {
    id: "moonshotai/kimi-vl-a3b-thinking:free",
    name: "Kimi-VL A3B Thinking",
    provider: "Moonshot AI (مونشوت)",
    category: "chinese",
    architecture: "MoE فائق التخفيف",
    params: "16B",
    paramsActive: "2.8B",
    context: 131072,
    capabilities: ["text", "image", "vision", "reasoning"],
    free: true,
    description: "MoE خفيف جدًا، 2.8B نشطة فقط، سريع جدًا، دقة عالية في الرياضيات والفهم البصري",
    site: "https://openrouter.ai/moonshotai/kimi-vl-a3b-thinking",
  },
  {
    id: "moonshotai/kimi-k1.5",
    name: "Kimi k1.5",
    provider: "Moonshot AI (مونشوت)",
    category: "chinese",
    architecture: "Transformer",
    context: 1000000,
    capabilities: ["text", "reasoning", "math", "code", "long-context"],
    free: false,
    description: "قدرة فائقة على حل المشكلات المعقدة والرياضيات وفهم النصوص الطويلة جدًا",
  },
  {
    id: "baidu/ernie-4.5",
    name: "ERNIE 4.5 (文心一言)",
    provider: "Baidu (بايدو)",
    category: "chinese",
    architecture: "Transformer",
    capabilities: ["text", "code", "search", "reasoning"],
    free: false,
    description: "من بايدو، أداء عالٍ بتكلفة أقل، يدمج تقنيات محرك البحث المتقدمة",
  },

  // ======= AMERICAN MODELS =======
  {
    id: "openai/o1",
    name: "ChatGPT o1",
    provider: "OpenAI",
    category: "american",
    architecture: "Transformer مع سلسلة تفكير",
    context: 200000,
    capabilities: ["text", "code", "reasoning", "math"],
    free: false,
    description: "المعيار الذهبي للتفاعل العام، دقة رياضية وتحليل معقد متقدم",
  },
  {
    id: "openai/o3-mini",
    name: "ChatGPT o3-mini",
    provider: "OpenAI",
    category: "american",
    architecture: "Transformer",
    context: 200000,
    capabilities: ["text", "code", "reasoning", "math"],
    free: false,
    description: "نسخة مصغرة من o3، دقة عالية في الرياضيات والبرمجة",
  },
  {
    id: "openai/gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    category: "american",
    architecture: "Multimodal Transformer",
    context: 128000,
    capabilities: ["text", "image", "code", "audio"],
    free: false,
    description: "نموذج OpenAI الرائد متعدد الوسائط، يفهم النص والصورة والصوت",
  },
  {
    id: "openai/gpt-4o-mini",
    name: "GPT-4o mini",
    provider: "OpenAI",
    category: "american",
    architecture: "Transformer",
    context: 128000,
    capabilities: ["text", "image", "code"],
    free: true,
    description: "نسخة خفيفة وسريعة من GPT-4o، مناسبة للتطبيقات اليومية",
  },
  {
    id: "anthropic/claude-opus",
    name: "Claude Opus",
    provider: "Anthropic",
    category: "american",
    architecture: "Transformer",
    context: 200000,
    capabilities: ["text", "code", "reasoning", "analysis"],
    free: false,
    description: "أقوى نموذج من Anthropic، يتفوق في النصوص الطويلة والتحليل العميق",
  },
  {
    id: "anthropic/claude-3.5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    category: "american",
    architecture: "Transformer",
    context: 200000,
    capabilities: ["text", "code", "reasoning"],
    free: true,
    description: "ممتاز في البرمجة والتحليل، توازن مثالي بين القوة والسرعة",
  },
  {
    id: "anthropic/claude-3-haiku",
    name: "Claude 3 Haiku",
    provider: "Anthropic",
    category: "american",
    architecture: "Transformer",
    context: 200000,
    capabilities: ["text", "code"],
    free: true,
    description: "أسرع نموذج من Anthropic، مثالي للردود السريعة",
  },
  {
    id: "google/gemini-2.5-pro-exp-03-25:free",
    name: "Gemini 2.5 Pro Exp",
    provider: "Google",
    category: "american",
    architecture: "Transformer مع ذاكرة متكررة",
    params: "300B-500B",
    context: 1000000,
    capabilities: ["text", "image", "code", "reasoning", "long-context"],
    free: true,
    description: "#1 على LMArena! مليون رمز سياق، تفكير متكرر متقدم",
    site: "https://openrouter.ai/google/gemini-2.5-pro-exp-03-25",
  },
  {
    id: "google/gemini-1.5-flash",
    name: "Gemini 1.5 Flash",
    provider: "Google",
    category: "american",
    architecture: "Transformer",
    context: 1000000,
    capabilities: ["text", "image", "code"],
    free: true,
    description: "سريع وفعال، يدعم مليون رمز سياق",
  },
  {
    id: "google/gemini-1.5-pro",
    name: "Gemini 1.5 Pro",
    provider: "Google",
    category: "american",
    architecture: "Transformer",
    context: 1000000,
    capabilities: ["text", "image", "code"],
    free: true,
    description: "قوي ومتوازن، مليون رمز سياق",
  },
  {
    id: "meta-llama/llama-4-maverick:free",
    name: "Llama 4 Maverick",
    provider: "Meta",
    category: "american",
    architecture: "MoE — 128 خبير",
    params: "400B",
    paramsActive: "17B",
    context: 256000,
    contextMax: 1000000,
    capabilities: ["text", "image", "code", "reasoning"],
    free: true,
    description: "أقوى نموذج مجاني! 400B MoE (17B نشطة)، 256K سياق، تفكير متعدد الوسائط",
    site: "https://openrouter.ai/meta-llama/llama-4-maverick",
  },
  {
    id: "meta-llama/llama-4-scout:free",
    name: "Llama 4 Scout",
    provider: "Meta",
    category: "american",
    architecture: "MoE — 16 خبير",
    params: "109B",
    paramsActive: "17B",
    context: 512000,
    contextMax: 10000000,
    capabilities: ["text", "image", "code"],
    free: true,
    description: "نشر فعال، 512K سياق (10M نظري)، نفس 17B نشطة مثل Maverick",
    site: "https://openrouter.ai/meta-llama/llama-4-scout",
  },
  {
    id: "nvidia/llama-3.1-nemotron-nano-8b-v1:free",
    name: "Nemotron Nano 8B",
    provider: "NVIDIA",
    category: "american",
    architecture: "Transformer مع تحسينات NVIDIA NeMo",
    params: "8B",
    context: 8192,
    capabilities: ["text", "code"],
    free: true,
    description: "من NVIDIA، محسّن بتقنيات NeMo و FlashAttention، توازن حجم/أداء",
    site: "https://openrouter.ai/nvidia/llama-3.1-nemotron-nano-8b-v1",
  },
  {
    id: "mistralai/mistral-small-3.1-24b-instruct:free",
    name: "Mistral Small 3.1 24B",
    provider: "Mistral AI",
    category: "american",
    architecture: "Transformer مع انتباه نافذة منزلق",
    params: "24B",
    context: 96000,
    contextMax: 128000,
    capabilities: ["text", "image", "code", "function-calling"],
    free: true,
    description: "24B مع 96K سياق، دعم استدعاء دوال JSON، متعدد اللغات",
    site: "https://openrouter.ai/mistralai/mistral-small-3.1-24b-instruct",
  },
  {
    id: "mistralai/mistral-small",
    name: "Mistral Small",
    provider: "Mistral AI",
    category: "american",
    architecture: "Transformer",
    context: 32768,
    capabilities: ["text", "code"],
    free: true,
    description: "نموذج Mistral الخفيف، سريع ومناسب للتطبيقات العامة",
  },
  {
    id: "mistralai/mistral-medium",
    name: "Mistral Medium",
    provider: "Mistral AI",
    category: "american",
    architecture: "Transformer",
    context: 32768,
    capabilities: ["text", "code"],
    free: true,
    description: "نموذج Mistral المتوسط، توازن بين القوة والسرعة",
  },
  {
    id: "nousresearch/deephermes-3-llama-3-8b-preview:free",
    name: "DeepHermes 3 8B",
    provider: "Nous Research",
    category: "american",
    architecture: "Llama 3 معدّل مع DPO",
    params: "8B",
    context: 8192,
    capabilities: ["text", "code"],
    free: true,
    description: "من Nous Research، ضبط دقيق على Llama 3 مع DPO وتوليد بيانات اصطناعية",
    site: "https://openrouter.ai/nousresearch/deephermes-3-llama-3-8b-preview",
  },

  // ======= OPENROUTER SPECIAL =======
  {
    id: "openrouter/optimus-alpha",
    name: "Optimus Alpha",
    provider: "OpenRouter",
    category: "openrouter",
    architecture: "Transformer",
    capabilities: ["text", "api"],
    free: true,
    description: "نموذج OpenRouter الداخلي، محسّن لتفاعلات API بكمون منخفض",
    site: "https://openrouter.ai/openrouter/optimus-alpha",
  },
  {
    id: "openrouter/quasar-alpha",
    name: "Quasar Alpha",
    provider: "OpenRouter",
    category: "openrouter",
    architecture: "Transformer مع انتباه محسّن بالمعرفة",
    capabilities: ["text", "reasoning", "knowledge"],
    free: true,
    description: "متخصص في الاستدلال وتمثيل المعرفة، تحقق وتصحيح ذاتي",
    site: "https://openrouter.ai/openrouter/quasar-alpha",
  },
];

export function getModelsByCategory(cat: ModelCategory): ModelSpec[] {
  return MODELS.filter(m => m.category === cat);
}

export function getFreeModels(): ModelSpec[] {
  return MODELS.filter(m => m.free);
}

export function getModelById(id: string): ModelSpec | undefined {
  return MODELS.find(m => m.id === id);
}

export function searchModels(query: string): ModelSpec[] {
  const q = query.toLowerCase();
  return MODELS.filter(m =>
    m.name.toLowerCase().includes(q) ||
    m.provider.toLowerCase().includes(q) ||
    m.description.toLowerCase().includes(q)
  );
}
